name: Deploy main branch to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy-ipfs:
    name: Deploy to IPFS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile # optional, --immutable

      - name: Build and optimize the code
        run: yarn build

      - name: Export production-ready code
        run: yarn export

      - name: Improve static for IPFS
        run:  cd out && npx all-relative

      - name: Upload to IPFS with Pinata
        uses: aquiladev/ipfs-action@v0.3.1
        id: pinata
        with:
          path: ./out
          service: pinata
          pinName: ${{ secrets.PIN_NAME || github.event.repository.name }}
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
